name: Monthly contributor report
on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date for metrics (YYYY-MM-DD)"
        required: true
      end_date:
        description: "End date for metrics (YYYY-MM-DD)"
        required: true

permissions:
  issues: write

jobs:
  contributor_report:
    name: contributor report
    runs-on: ubuntu-latest

    steps:

    - name: Get dates for last month
      shell: bash
      run: |
        # Calculate the first day of the previous month
        start_date=$(date -d "last month" +%Y-%m-01)

        # Calculate the last day of the previous month
        end_date=$(date -d "$start_date +1 month -1 day" +%Y-%m-%d)

        #Set an environment variable with the date range
        echo "START_DATE=$start_date" >> "$GITHUB_ENV"
        echo "END_DATE=$end_date" >> "$GITHUB_ENV"

    - name: Run contributor action
      uses: github/contributors@135b0430e856ade27175cbd1d4e1e11b0dd8ef95
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        START_DATE: ${{ env.START_DATE }}
        END_DATE: ${{ env.END_DATE }}
        REPOSITORY: github/issue-metrics
        SPONSOR_INFO: "true"

    - name: Create issue
      uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94
      with:
        title: Monthly contributor report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./contributors.md
        assignees: zkoppert
