name: Monthly issue metrics

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date for metrics (YYYY-MM-DD)"
        required: true
      end_date:
        description: "End date for metrics (YYYY-MM-DD)"
        required: true

permissions:
  contents: read

jobs:
  build:
    name: Issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Set date range
        run: |
          # Use the provided input values
          start_date=${{ github.event.inputs.start_date }}
          end_date=${{ github.event.inputs.end_date }}

          # Set environment variables with the date range
          echo "start_date=$start_date" >> $GITHUB_ENV
          echo "end_date=$end_date" >> $GITHUB_ENV

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SEARCH_QUERY: 'repo:sudeepmenonnc/issue-metrics created:${{ env.start_date }}..${{ env.end_date }} -reason:"not planned"'

     - name: Create issue
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: Monthly issue metrics report
        token: ${{ secrets.GH_TOKEN }}
        content-filepath: ./issue_metrics.md         

  
