name: 'Close stale issues'
on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date for metrics (YYYY-MM-DD)"
        required: true
      end_date:
        description: "End date for metrics (YYYY-MM-DD)"
        required: true
permissions:
  issues: write
  pull-requests: read

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
        with:
          stale-issue-message: 'This issue is stale because it has been open 21 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 35 days with no activity.'
          days-before-stale: 21
          days-before-close: 14
          days-before-pr-close: -1
          exempt-issue-labels: keep
